import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LeftMenu from "@/components/left-menu";
import { Providers } from "@/components/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {




  return (
    <html lang="en" className="dark">

      {
        true ? (
          <body className={"min-h-screen bg-background text-foreground grid grid-cols-body-small xl:grid-cols-body-big " + inter.className}>
            <Providers>
              <LeftMenu />
              {children}
            </Providers>
          </body>) : (
          <body className={"min-h-screen bg-background text-foreground " + inter.className}>
            <Providers>
              {children}
            </Providers>
          </body>
        )
      }



    </html>
  );
}
